GET http://localhost:4000/fruits

###

GET http://localhost:4000/fruits/12


###

POST http://localhost:4000/fruits
Content-Type: application/json

{
    "name": "Omena2",
    "id" : 11060,
    "energyKcal": 150,
    "protein": 1.5,
    "fat": 0.2,
    "carbohydrate": 17.4
}